services:
  camunda:
    image: camunda/camunda-bpm-platform:run-latest
    ports:
      - "8081:8080"
      - "8443:8443"
    command: ["./start.sh", "--production"]
    volumes:
      - ./production.yml:/camunda/configuration/production.yml
#    environment:
#      - CAMUNDA_BPM_RUN_CONFIGURATION=production
#      - LDAP_ENABLED=true
#      - LDAP_URL=ldap://172.19.228.72:389
#      - LDAP_BASE_DN=dc=permgp7,dc=ru
#      - LDAP_MANAGER_DN=cn=admin,dc=permgp7,dc=ru
#      - LDAP_MANAGER_PASSWORD=Gkb6CodCod
#      - LDAP_USER_SEARCH_BASE=dc=permgp7,dc=ru
#      - LDAP_USER_SEARCH_FILTER=(uid={0})
#      - LDAP_USER_ID_ATTRIBUTE=uid
#      - LDAP_FIRST_NAME_ATTRIBUTE=givenName
#      - LDAP_LAST_NAME_ATTRIBUTE=sn
#      - LDAP_EMAIL_ATTRIBUTE=mail
#      - LDAP_GROUP_SEARCH_BASE=dc=permgp7,dc=ru
#      - LDAP_GROUP_SEARCH_FILTER=(objectClass=posixGroup)
#      - LDAP_GROUP_ID_ATTRIBUTE=cn
#      - LDAP_GROUP_NAME_ATTRIBUTE=cn
#      - LDAP_GROUP_MEMBER_ATTRIBUTE=memberUid
#      - LDAP_DEBUG=true
#      - LOGGING_LEVEL_ORG_CAMUNDA_BPM_IDENTITY_LDAP=DEBUG
#      - LDAP_AUTHORIZATION_ENABLED=true
#      - LDAP_GROUP_ADMIN=camunda-admin
#      - LDAP_GROUP_READER=camunda-reader
#      - LDAP_GROUP_WRITER=camunda-writer
